version: '3.8'

services:
  openldap:
    build:
      context: ./nginx/ldif
      dockerfile: Dockerfile.openldap
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Dev Company"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: "dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "admin123"
      LDAP_CONFIG_PASSWORD: "config123"
      LDAP_TLS: "false"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./nginx/ldif:/ldif:ro
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=example,dc=com", "-w", "admin123", "-b", "dc=example,dc=com"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ldap_network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"  # For development only
    ports:
      - "8080:80"
    depends_on:
      - openldap
    networks:
      - ldap_network

  loadbalancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/local/openresty/nginx/html
      - ./nginx/lua:/usr/local/openresty/nginx/lua
    depends_on:
      - openldap
    networks:
      - ldap_network

volumes:
  ldap_data:
  ldap_config:

networks:
  ldap_network:
    driver: bridge 