version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Dev Company"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN: "dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "admin123"  # Change this in production
      LDAP_CONFIG_PASSWORD: "config123"  # Change this in production
      LDAP_TLS: "false"  # For development only
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - ldap_network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"  # For development only
    ports:
      - "8080:80"
    depends_on:
      - openldap
    networks:
      - ldap_network

  loadbalancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/local/openresty/nginx/html
      - ./nginx/lua:/usr/local/openresty/nginx/lua
    depends_on:
      - openldap
    networks:
      - ldap_network

volumes:
  ldap_data:
  ldap_config:

networks:
  ldap_network:
    driver: bridge 